apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.14.0
    helm:
      values: |
        replicaCount: 1
        clusterName: prod-cluster
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::217340893387:role/eksctl-prod-cluster-addon-iamserviceaccount-k-Role1-KiALSQ5oNM3L
        region: us-east-1
        vpcId: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
