apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-workernode-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.37.0
    helm:
      values: |
        fullnameOverride: cluster-autoscaler
        autoDiscovery:
          clusterName: prod-cluster
        awsRegion: us-east-1
        rbac:
          create: false
        serviceAccount:
          create: false
          name: cluster-autoscaler
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::217340893387:role/eksctl-prod-cluster-addon-iamserviceaccount-k-Role1-PQ88ZbkUP2RH
        extraArgs:
          balance-similar-node-groups: true
          skip-nodes-with-system-pods: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace: false
